[connections.connection_name_testing_purposes]
account = "SFSEHOL-DRY_RUN_FLEET_INTELLIGENCE_NOV_BDTTVY"
user = "user"
password = "sn0wf@ll"
role = "ATTENDEE_ROLE"
warehouse = "DEFAULT_WH"
database = "FLEET_INTELLIGENCE"
schema = "FLEET_INTELLIGENCE"

[default_connection]
connection = "connection_name_testing_purposes"
